#! /usr/bin/bash

#### 1- Lists all files (tables) in the database directory to make user choose ######
echo "Here are the available tables in $dbName"
ls ~/DBMS/$dbName/


PS3="Please choose an option [1-2]: "   
    
select option in "Delete by value" "Exit"; do
     case $option in
        
        "Delete by value")
             
	####2- Ask for the table name and check if it exists
	read -p "Enter the name of the table to delete from : " tName

	### 3- Create variables to hold paths of table
	table_path=~/DBMS/$dbName/$tName

	### 4- Check if the table exists
	if [ -f "$table_path" ]; then
        read -p "Enter the column name to search by: " search_col
        
### 16 - Find the column index for the search column
        search_col_index=$(awk -v col="$search_col" -F: '
        NR == 1 {
            for (i = 1; i <= NF; i++) {
                if ($i == col) {
                    print i
                    exit
                }
            }
        }
        ' "$table_path")
    
### 17 - Check if the column exists
        if  [[ -z $search_col_index ]]; then
            echo "Column '$search_col' not found."

            else
        

 ######### (2) Enter the value to search for ########################
        read -p "Enter the value to search for: " search_value

### 18 - Find the row number matching the search condition
        row_number=$(awk -v col="$search_col_index" -v val="$search_value" -F: '
        $col == val { print NR }
        ' "$table_path")

### 19- Validate if a matching row exists
        if [[ -z $row_number ]]; then
            echo "No rows found where '$search_col' equals '$search_value'."

        else

### 9- DELETE THE ROW
                awk -v row="$row_number" 'NR != row { print $0 }' "$table_path" > tmp && mv tmp "$table_path"

                ### AWK skips the row corresponding to `row_number` and writes all other rows to a temporary file `tmp`.
                ### We replace the original table file with the temporary file.

                echo "Row deleted successfully."
       
	       fi
	       fi
       
      else
    	echo "Table $tName does not exist."
fi
                ;;

            "Exit")
            	echo "Exiting delete menu.."
                break 
                ;;

            *)
                echo "Invalid option. Please try again."
                ;;
        esac
        
    done
