#!/usr/bin/bash

# Prompt for the table name
read -p "Enter the name of the table you want to drop: " tname
table=${tname,,}  # Convert to lowercase

# Check if the table exists
if [ -e "$HOME/DBMS/$dbName/$table" ]; then
    # Confirm the action with the user
    read -p "Are you sure you want to drop $table? yes/no: " answer
    if [[ $answer =~ ^yes$ ]]; then
        # Remove the table and its metadata file
        rm "$HOME/DBMS/$dbName/$table" "$HOME/DBMS/$dbName/.meta$table"
        echo "Table $table has been dropped. Don't come at me..."
    elif [[ $answer =~ ^no$ ]]; then
        echo "Great choice! Always think twice before dropping a table."
    else
        echo "Did not get that, try again."
    fi
else
    echo "Table does not exist."
fi

