#! /usr/bin/bash
validate_str() {
    if [[ "$1" =~ ^[a-zA-Z0-9_]+$ ]]; then
        # String must only contain letters, numbers, or underscores
        return 0 # Valid
    else
        return 1 # Invalid
    fi
}

# Ask the user for the table name to drop
read -p "Enter the name of the table you want to drop: " tname
	table=${tname,,}


	    
	    # Validate the table name
	    if ! validate_str "$tname"; then
		echo "Invalid name. table names must only contain letters, numbers, or underscores: $tname"
	    else
		table=${tname,,}  # Convert to lowercase for consistency
		if [ -d "$table" ]; then
		    # Confirm deletion with user
		    read -p "Are you sure you want to drop $table? yes/no: " answer
		    if [[ $answer =~ ^yes$ ]]; then
		        rm -r "$table"
		        echo "Table '$table' has been dropped."
		    elif [[ $answer =~ ^no$ ]]; then
		        echo "Great choice! Always think twice before dropping a table."
		    else
		        echo "Unrecognized input. Try again."
		    fi
		else
		    echo "table '$table' does not exist."
		fi
	    fi
	    ;;
